import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { AuthProvider } from "./context/AuthContext";
import "leaflet/dist/leaflet.css";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Add the external stylesheet link using the Metadata API
  links: [
    {
      rel: "stylesheet",
      href: "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css",
      integrity: "sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=",
      crossOrigin: "",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <AuthProvider>
        {children}
        </AuthProvider>
        <Footer />
        </body>
    </html>
  );
}
